language: python
python:
  - "3.9"
# command to install dependencies
install:
    pip install -r requirements_dev.txt
# command to run tests
env:
  - MONGO_URI="mongodb://test:test@localhost:27017/thebookshelf"
script:
  - python -m unittest discover -s test/src/bookshelf/ -p "*_test.py"  -v
  - python -m unittest discover -s test/html_test/*_view -p "*_test.py" -v
